name: automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MERGE_METHOD: squash
  MERGE_DELETE_BRANCH: true
  MERGE_RETRIES: 3
  MERGE_RETRY_SLEEP: 60000

jobs:
  automerge-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Automerge
        if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]'
        uses: pascalgn/automerge-action@v0.8.1
        env:
          UPDATE_LABELS: NEVER_MATCHES
          MERGE_COMMIT_MESSAGE: automatic
